export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNLOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWNLOAD_PRODUCTS_SUCCESS';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWNLOAD_PRODUCTS_ERROR';
