export const ADD_PRODUCT = 'ADD_PRODUCTO';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCTO_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCTO_ERROR';

export const START_DOWNLOAD_PRODUCTS = 'START_DOWNOAD_PRODUCTS';
export const DOWNLOAD_PRODUCTS_SUCCESS = 'DOWLOAD_PRODUCTS_SUCCESS';
export const DOWNLOAD_PRODUCTS_ERROR = 'DOWLOAD_PRODUCTS_ERROR';
